name: app
description: robo_zipa
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore:
  firebase_core:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  dio:
  get_it: ^7.6.2
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - assets/ss.png
  #   - assets/svg/

  fonts:
    - family: Spartan
      fonts:
        - asset: fonts/league-spartan-v11-latin-700.ttf
        - asset: fonts/league-spartan-v11-latin-regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
